### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by hiratecs21** [piazzatron/anki-smart-notes#46]
I've noticed an issue with Smart Notes. Whenever I update the app, the Smart Fields I previously created disappear.

I’m also having trouble with the tab size. It’s too large, extending below the taskbar, so I can’t see or access the “OK” and “Cancel” buttons. The window doesn’t seem to be adjustable, which makes it hard to work with. Is there a solution to resize it or make it more flexible?

Thanks for your help!

<img width="693" alt="it looks like this" src="https://github.com/user-attachments/assets/fd5a3d7c-4af2-46a0-a43c-751e64b41010">

**Comment by piazzatron** [comment]
Hey @hiratecs21, thanks for flagging these.

- I'll fix the tab bar issue, didn't see in my testing since I'm on a larger screen!
- Losing your smart notes on update is very strange, haven't seen this before 👀. I'll need a bit more info: do you mean when you're updating Anki, or Smart Notes? How are you going about updating it? What platform are you running?


-

**Comment by hiratecs21** [comment]
Thanks for the answer! I'm on Windows 10, using Anki version 24.06.3, and I was referring to updating the addon, not Anki. Anki notified me about an update for the addon (the latest update for Smart Fields for images notes), so I clicked to update it. After reopening Anki, my Smart Notes account seemed to be logged out, so I logged in again. When I checked, all my Smart Fields (both audio and text) were missing. This wasn’t the first time it happened; I remember using it previously, and the fields also disappeared after updating the addon.

**Comment by piazzatron** [comment]
Got it. I'll update here when I've figured out what's going on (updates preserve state for me) - might be a little bit.

**Comment by piazzatron** [comment]
Hey @hiratecs21, the sizing issue on small screens should be fixed on 2.5.3. If you are able to update, could let me know if your fields stick around this time?

**Comment by hiratecs21** [comment]
Oh sure!

**Comment by hiratecs21** [comment]
This time, the smart fields are still here. However, I still have some problems with tab sizing. I'll try to record you a short video to you.

**Comment by hiratecs21** [comment]
Oh forget about it. I can't select Ok or Cancel in the main tab of Smart Notes, but it doesn't matter since it works when I close with the X close button in the top right. Thanks for the fixing!

**Comment by piazzatron** [comment]
Yay glad to hear it's working! Closing this, feel free to re-open if you encounter any other issues
